spring:
  application:
    name: audit-compliance-service
  datasource:
    url: jdbc:mysql://localhost:3306/audit_compliance_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
  cloud:
    config:
      enabled: false

server:
  port: 8087

eureka:
  instance:
    # Ensures the service registers with its IP address, solving the UnknownHost issue
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT Configuration
jwt:
  secret: Y2Y4ZTM1YmYtYjYyMC00ZDllLTlhZTMtZDY2ZDU4ZTMxZmE5Cg==